import { and, asc, eq, gt, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { players, profiles, rooms, targets } from "../../../db/schema";

const CODE_CHARS="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const TASKS=[
  {name:"Align star map",room:"OBSERVATORY",x:-12,z:-8},{name:"Stabilize samples",room:"LAB",x:0,z:-10},
  {name:"Prime coolant",room:"REACTOR",x:12,z:-7},{name:"Decode signal",room:"COMMS",x:-13,z:1},
  {name:"Restore archives",room:"ARCHIVE",x:12,z:2},{name:"Calibrate shields",room:"SHIELD BAY",x:-10,z:10},
  {name:"Chart the anomaly",room:"NAVIGATION",x:2,z:10},{name:"Reroute power",room:"CORE",x:1,z:0},
];
type Body={action?:string;name?:string;roomCode?:string;playerId?:string;token?:string;profileKey?:string;x?:number;z?:number;heading?:number;targetId?:string;targetPlayerId?:string};
const cleanName=(v:unknown)=>typeof v==="string"?v.trim().replace(/\s+/g," ").slice(0,18):"";
const cleanCode=(v:unknown)=>typeof v==="string"?v.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6):"";
const cleanKey=(v:unknown)=>typeof v==="string"?v.replace(/[^a-zA-Z0-9-]/g,"").slice(0,64):"";
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,Number.isFinite(v)?v:0));
const makeCode=()=>Array.from(crypto.getRandomValues(new Uint8Array(6)),b=>CODE_CHARS[b%CODE_CHARS.length]).join("");

async function ensureProfile(deviceKey:string,name:string,now:number){const db=getDb();const [p]=await db.select().from(profiles).where(eq(profiles.deviceKey,deviceKey)).limit(1);if(p){await db.update(profiles).set({name,updatedAt:now}).where(eq(profiles.id,p.id));return p.id}const id=crypto.randomUUID();await db.insert(profiles).values({id,deviceKey,name,createdAt:now,updatedAt:now});return id}
async function seedTasks(roomId:string,now:number){const db=getDb();await db.delete(targets).where(eq(targets.roomId,roomId));for(let i=0;i<TASKS.length;i++){const t=TASKS[i];await db.insert(targets).values({id:crypto.randomUUID(),roomId,level:1,targetIndex:i,x:t.x,z:t.z,hp:1,maxHp:1,kind:`${t.room}|${t.name}`,updatedAt:now})}}
async function readRoom(code:string){const db=getDb();const [room]=await db.select().from(rooms).where(eq(rooms.code,code)).limit(1);if(!room)return null;const squad=await db.select().from(players).where(eq(players.roomId,room.id)).orderBy(asc(players.slot));const jobs=await db.select().from(targets).where(eq(targets.roomId,room.id)).orderBy(asc(targets.targetIndex));const leaders=await db.select({name:profiles.name,totalScore:profiles.totalScore,matches:profiles.matches}).from(profiles).orderBy(sql`${profiles.totalScore} desc`).limit(8);return{room,squad,jobs,leaders}}
function gameState(data:NonNullable<Awaited<ReturnType<typeof readRoom>>>,viewerId:string){const reveal=data.room.status==="victory";const viewer=data.squad.find(p=>p.id===viewerId);return{room:{code:data.room.code,status:data.room.status,hostPlayerId:data.room.hostPlayerId,winner:data.room.status==="victory"?(data.room.level===2?"GLITCHES":"OPERATORS"):null,startedAt:data.room.startedAt},myRole:viewer?.weapon??null,players:data.squad.map(({token:_t,profileId:_p,roomId:_r,weapon,...p})=>({...p,role:reveal?weapon:undefined})),tasks:data.jobs.map(t=>{const [room,name]=t.kind.split("|");return{id:t.id,room,name,x:t.x,z:t.z,done:t.hp===0}}),leaderboard:data.leaders}}
function fail(error:unknown){console.error(error);return Response.json({error:"The station signal flickered. Try again."},{status:500})}
async function setVictory(roomId:string,winner:"OPERATORS"|"GLITCHES",now:number){const db=getDb();await db.update(rooms).set({status:"victory",level:winner==="GLITCHES"?2:1,updatedAt:now}).where(eq(rooms.id,roomId))}
async function checkBalance(roomId:string,now:number){const db=getDb();const squad=await db.select().from(players).where(eq(players.roomId,roomId));const active=squad.filter(p=>p.perk==="ACTIVE"),glitches=active.filter(p=>p.weapon==="GLITCH").length,operators=active.length-glitches;if(glitches===0)await setVictory(roomId,"OPERATORS",now);else if(glitches>=operators)await setVictory(roomId,"GLITCHES",now)}

export async function GET(request:Request){try{const u=new URL(request.url),code=cleanCode(u.searchParams.get("room")),data=await readRoom(code);if(!data)return Response.json({error:"Room not found."},{status:404});const playerId=u.searchParams.get("player")??"",token=u.searchParams.get("token")??"";if(!data.squad.some(p=>p.id===playerId&&p.token===token))return Response.json({error:"Your station session is invalid."},{status:401});return Response.json(gameState(data,playerId))}catch(e){return fail(e)}}

export async function POST(request:Request){try{const body=await request.json() as Body,db=getDb(),now=Date.now();
  if(body.action==="create"){const name=cleanName(body.name),key=cleanKey(body.profileKey);if(name.length<2||key.length<8)return Response.json({error:"Enter a valid codename."},{status:400});let code=makeCode();for(let i=0;i<5;i++){const [hit]=await db.select({id:rooms.id}).from(rooms).where(eq(rooms.code,code)).limit(1);if(!hit)break;code=makeCode()}const roomId=crypto.randomUUID(),playerId=crypto.randomUUID(),token=crypto.randomUUID(),profileId=await ensureProfile(key,name,now);await db.batch([db.insert(rooms).values({id:roomId,code,hostPlayerId:playerId,createdAt:now,updatedAt:now}),db.insert(players).values({id:playerId,roomId,profileId,token,name,slot:0,x:-4,z:5,weapon:"OPERATOR",perk:"ACTIVE",joinedAt:now,lastSeenAt:now})]);return Response.json({...gameState((await readRoom(code))!,playerId),playerId,token},{status:201})}
  if(body.action==="join"){const name=cleanName(body.name),code=cleanCode(body.roomCode),key=cleanKey(body.profileKey),data=await readRoom(code);if(name.length<2||key.length<8)return Response.json({error:"Enter a valid codename."},{status:400});if(!data)return Response.json({error:"Room not found."},{status:404});if(data.room.status!=="waiting")return Response.json({error:"This investigation has already started."},{status:409});if(data.squad.length>=8)return Response.json({error:"This station is full."},{status:409});if(data.squad.some(p=>p.name.toLowerCase()===name.toLowerCase()))return Response.json({error:"That codename is already in use."},{status:409});const id=crypto.randomUUID(),token=crypto.randomUUID(),profileId=await ensureProfile(key,name,now),slot=data.squad.length;await db.insert(players).values({id,roomId:data.room.id,profileId,token,name,slot,x:-7+slot*2,z:5,weapon:"OPERATOR",perk:"ACTIVE",joinedAt:now,lastSeenAt:now});return Response.json({...gameState((await readRoom(code))!,id),playerId:id,token},{status:201})}
  const code=cleanCode(body.roomCode),data=await readRoom(code);if(!data)return Response.json({error:"Room not found."},{status:404});const actor=data.squad.find(p=>p.id===body.playerId&&p.token===body.token);if(!actor)return Response.json({error:"Session expired."},{status:401});
  if(body.action==="start"){if(actor.id!==data.room.hostPlayerId)return Response.json({error:"Only the host can begin."},{status:403});if(data.squad.length<4)return Response.json({error:"At least 4 players are required."},{status:409});await seedTasks(data.room.id,now);const shuffled=[...data.squad].sort(()=>crypto.getRandomValues(new Uint32Array(1))[0]-.5),glitchCount=data.squad.length>=7?2:1,glitches=new Set(shuffled.slice(0,glitchCount).map(p=>p.id));for(const p of data.squad)await db.update(players).set({weapon:glitches.has(p.id)?"GLITCH":"OPERATOR",perk:"ACTIVE",score:0,hits:0,shots:0,lastShotAt:0}).where(eq(players.id,p.id));await db.update(rooms).set({status:"playing",level:1,startedAt:now,updatedAt:now}).where(eq(rooms.id,data.room.id))
  }else if(body.action==="move"){if(data.room.status!=="playing"||actor.perk!=="ACTIVE")return Response.json({error:"Movement is currently locked."},{status:409});await db.update(players).set({x:clamp(Number(body.x),-16,16),z:clamp(Number(body.z),-12,12),heading:clamp(Number(body.heading),-20,20),lastSeenAt:now}).where(eq(players.id,actor.id))
  }else if(body.action==="task"){if(data.room.status!=="playing"||actor.perk==="QUARANTINED")return Response.json({error:"Tasks are unavailable."},{status:409});const task=data.jobs.find(t=>t.id===body.targetId&&t.hp>0);if(!task)return Response.json({error:"That task is already complete."},{status:409});if(Math.hypot(task.x-actor.x,task.z-actor.z)>5)return Response.json({error:"Move closer to the terminal."},{status:409});if(actor.weapon!=="GLITCH"){await db.update(targets).set({hp:0,updatedAt:now}).where(and(eq(targets.id,task.id),gt(targets.hp,0)));await db.update(players).set({score:sql`${players.score}+1`}).where(eq(players.id,actor.id));const left=await db.select().from(targets).where(and(eq(targets.roomId,data.room.id),gt(targets.hp,0)));if(left.length===0)await setVictory(data.room.id,"OPERATORS",now)}
  }else if(body.action==="disrupt"){if(data.room.status!=="playing"||actor.weapon!=="GLITCH"||actor.perk!=="ACTIVE")return Response.json({error:"You cannot disrupt the station."},{status:403});if(now-actor.lastShotAt<10000)return Response.json({error:"Disruption is recharging."},{status:429});const completed=data.jobs.filter(t=>t.hp===0);if(completed.length){const t=completed[Math.floor(Math.random()*completed.length)];await db.update(targets).set({hp:1,updatedAt:now}).where(eq(targets.id,t.id))}await db.update(players).set({lastShotAt:now}).where(eq(players.id,actor.id))
  }else if(body.action==="erase"){if(data.room.status!=="playing"||actor.weapon!=="GLITCH"||actor.perk!=="ACTIVE")return Response.json({error:"Action unavailable."},{status:403});if(now-actor.lastShotAt<15000)return Response.json({error:"Glitch pulse is recharging."},{status:429});const victim=data.squad.find(p=>p.id===body.targetPlayerId&&p.id!==actor.id&&p.perk==="ACTIVE");if(!victim||Math.hypot(victim.x-actor.x,victim.z-actor.z)>4)return Response.json({error:"No player is close enough."},{status:409});await db.update(players).set({perk:"QUARANTINED"}).where(eq(players.id,victim.id));await db.update(players).set({lastShotAt:now}).where(eq(players.id,actor.id));await checkBalance(data.room.id,now)
  }else if(body.action==="meeting"){if(data.room.status!=="playing"||actor.perk!=="ACTIVE")return Response.json({error:"You cannot call a meeting now."},{status:409});await db.update(players).set({hits:0}).where(eq(players.roomId,data.room.id));await db.update(rooms).set({status:"meeting",updatedAt:now}).where(eq(rooms.id,data.room.id))
  }else if(body.action==="vote"){if(data.room.status!=="meeting"||actor.perk!=="ACTIVE")return Response.json({error:"Voting is closed."},{status:409});const target=data.squad.find(p=>p.id===body.targetPlayerId&&p.perk==="ACTIVE");if(!target)return Response.json({error:"Choose an active player."},{status:400});await db.update(players).set({hits:target.slot+1}).where(eq(players.id,actor.id));const fresh=(await readRoom(code))!,active=fresh.squad.filter(p=>p.perk==="ACTIVE");if(active.every(p=>p.hits>0)){const tally=new Map<number,number>();for(const p of active)tally.set(p.hits,(tally.get(p.hits)??0)+1);const ranked=[...tally.entries()].sort((a,b)=>b[1]-a[1]);if(ranked.length===1||ranked[0][1]>ranked[1][1]){const voted=fresh.squad.find(p=>p.slot===ranked[0][0]-1);if(voted)await db.update(players).set({perk:"QUARANTINED"}).where(eq(players.id,voted.id))}await db.update(rooms).set({status:"playing",updatedAt:now}).where(eq(rooms.id,data.room.id));await checkBalance(data.room.id,now)}
  }else if(body.action==="reset"){if(actor.id!==data.room.hostPlayerId)return Response.json({error:"Only the host can restart."},{status:403});await db.delete(targets).where(eq(targets.roomId,data.room.id));await db.update(players).set({weapon:"OPERATOR",perk:"ACTIVE",score:0,hits:0,shots:0,lastShotAt:0,x:0,z:5}).where(eq(players.roomId,data.room.id));await db.update(rooms).set({status:"waiting",level:1,startedAt:null,updatedAt:now}).where(eq(rooms.id,data.room.id))
  }else return Response.json({error:"Unknown action."},{status:400});return Response.json(gameState((await readRoom(code))!,actor.id))
}catch(e){return fail(e)}}
