"use client";
import { useEffect, useRef } from "react";
import * as THREE from "three";

type Pilot = { id:string; slot:number; x:number; z:number; heading:number; name:string };
type Drone = { id:string; x:number; z:number; hp:number; maxHp:number; kind:string };
type Props = { level:number; players:Pilot[]; targets:Drone[]; meId:string; tracker?:boolean; quality?:"performance"|"balanced"|"cinematic"; reduceMotion?:boolean; onTarget?:(id:string)=>void };
const COLORS=[0x36d7c7,0xffb000,0xff5b57,0x7899ff];

export function ArenaScene({level,players,targets,meId,tracker=false,quality="balanced",reduceMotion=false,onTarget}:Props){
  const host=useRef<HTMLDivElement>(null); const latest=useRef({players,targets,meId,tracker,onTarget}); latest.current={players,targets,meId,tracker,onTarget};
  useEffect(()=>{
    if(!host.current)return; const mount=host.current, scene=new THREE.Scene(); scene.background=new THREE.Color(level===2?0xa9c6cf:level===3?0x86a977:0x516268); scene.fog=new THREE.Fog(scene.background,28,64);
    const camera=new THREE.PerspectiveCamera(58,mount.clientWidth/Math.max(1,mount.clientHeight),.1,120); camera.position.set(0,15,17);
    const probe=document.createElement("canvas"),webgl=probe.getContext("webgl2")||probe.getContext("webgl"); if(!webgl){mount.classList.add("arena-fallback");const note=document.createElement("span");note.textContent="3D VIEW UNAVAILABLE · TARGET CONTROLS ARE STILL ACTIVE";mount.appendChild(note);return()=>{mount.classList.remove("arena-fallback");mount.replaceChildren();};}
    let renderer:THREE.WebGLRenderer; try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});}catch{mount.classList.add("arena-fallback");const note=document.createElement("span");note.textContent="3D VIEW UNAVAILABLE · TARGET CONTROLS ARE STILL ACTIVE";mount.appendChild(note);return()=>{mount.classList.remove("arena-fallback");mount.replaceChildren();};}
    renderer.setSize(mount.clientWidth,mount.clientHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,quality==="cinematic"?2:quality==="balanced"?1.5:1));renderer.shadowMap.enabled=quality!=="performance";renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;mount.appendChild(renderer.domElement);
    scene.add(new THREE.HemisphereLight(level===1?0xc6e1e2:0xe8f4ff,level===3?0x30451e:0x433a2a,2.35));const sun=new THREE.DirectionalLight(level===2?0xfff4dc:0xffe3ad,3.6);sun.position.set(-12,24,8);sun.castShadow=quality!=="performance";sun.shadow.mapSize.set(quality==="cinematic"?2048:1024,quality==="cinematic"?2048:1024);scene.add(sun);
    const sky=new THREE.Mesh(new THREE.SphereGeometry(85,24,16),new THREE.ShaderMaterial({side:THREE.BackSide,uniforms:{top:{value:new THREE.Color(level===3?0x355d63:0x31506d)},bottom:{value:new THREE.Color(level===2?0xd8c9a8:0x9fae9c)}},vertexShader:"varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}",fragmentShader:"uniform vec3 top;uniform vec3 bottom;varying vec3 v;void main(){float h=clamp(normalize(v).y*.65+.45,0.,1.);gl_FragColor=vec4(mix(bottom,top,h),1.);}"}));scene.add(sky);
    if(quality!=="performance"){const count=quality==="cinematic"?220:100,positions=new Float32Array(count*3);for(let i=0;i<count;i++){positions[i*3]=(Math.random()-.5)*58;positions[i*3+1]=1+Math.random()*14;positions[i*3+2]=(Math.random()-.5)*58;}const geo=new THREE.BufferGeometry();geo.setAttribute("position",new THREE.BufferAttribute(positions,3));scene.add(new THREE.Points(geo,new THREE.PointsMaterial({color:level===3?0xffd37a:0xb9f2ea,size:.055,transparent:true,opacity:.55})))}
    const mat=(color:number,rough=.75)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.08});
    const addBox=(w:number,h:number,d:number,color:number,x:number,y:number,z:number,rot=0)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);m.rotation.y=rot;m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;};
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(65,65),mat(level===1?0x665f43:level===2?0x6f7777:0x53753f,1));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
    if(level===1){
      const colors=[0x24618b,0xb63d35,0xc49b2d]; for(let i=0;i<26;i++){const row=Math.floor(i/7),col=i%7;const x=-15+col*5+(row%2)*1.4,z=-12+row*7;const h=i%5===0?3.8:2.1;addBox(4.1,h,2.1,colors[(i+row)%3],x,h/2,z,(i%3-1)*.05);if(i%4===0)addBox(4.4,.15,.5,0x725334,x,h+.18,z);}
      addBox(9,5,8,0x303b3e,14,2.5,-12);addBox(2.8,3.2,.2,0x1b2426,14,1.7,-7.9);
    }else if(level===2){
      addBox(8,.08,56,0x353c3d,0,.06,0);for(let z=-22;z<24;z+=7)addBox(.25,.12,2.8,0xf3df9b,0,.1,z);addBox(5,1.6,2.2,0xc59525,13,.8,-10);addBox(3,2,2.2,0x2b6380,-13,1,-8);
      const ocean=new THREE.Mesh(new THREE.PlaneGeometry(65,19),new THREE.MeshStandardMaterial({color:0x326b77,roughness:.35,metalness:.18}));ocean.rotation.x=-Math.PI/2;ocean.position.set(0,-.04,-25);scene.add(ocean);
      const wreck=new THREE.Group();const body=new THREE.Mesh(new THREE.CylinderGeometry(.75,1.1,9,8),mat(0x485554,.7));body.rotation.z=Math.PI/2;wreck.add(body);const wing=new THREE.Mesh(new THREE.BoxGeometry(10,.18,2.1),mat(0x3f4a49,.8));wreck.add(wing);wreck.position.set(-8,1.1,-14);wreck.rotation.y=-.2;scene.add(wreck);
      for(let i=0;i<12;i++){const x=-16+(i%6)*6,z=8+Math.floor(i/6)*5;addBox(2.4,.25,1.2,0x5b4632,x,.75,z);addBox(.18,1.4,.18,0x4a3829,x-1,.35,z);addBox(.18,1.4,.18,0x4a3829,x+1,.35,z);}
    }else{
      for(let i=0;i<24;i++){const a=i*.91,r=10+(i%5)*4,x=Math.cos(a)*r,z=Math.sin(a)*r;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.22,.3,2.3,8),mat(0x60442a));trunk.position.set(x,1.15,z);scene.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.45,3.2,9),mat(i%3===0?0x3b6d38:0x2f5c32));crown.position.set(x,3.2,z);crown.castShadow=true;scene.add(crown);}
      for(let i=0;i<11;i++){const hill=new THREE.Mesh(new THREE.SphereGeometry(3.5+(i%3),18,10),mat(0x567944,1));hill.scale.y=.28;hill.position.set(-20+(i%5)*10,-.2,-19+Math.floor(i/5)*35);scene.add(hill);}
      for(let i=0;i<50;i++){const blade=new THREE.Mesh(new THREE.ConeGeometry(.09,.8,4),mat(0xa48f42,1));blade.position.set(-18+(i%10)*4,.4,-13+Math.floor(i/10)*6);scene.add(blade);}
    }
    const pilotMeshes=new Map<string,THREE.Group>(), droneMeshes=new Map<string,THREE.Group>();let clickables:THREE.Object3D[]=[];
    const makePilot=(p:Pilot)=>{const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CylinderGeometry(.48,.6,1.45,12),mat(COLORS[p.slot%COLORS.length],.55));body.position.y=1.15;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,14,10),mat(0xe2b18c,.8));head.position.y=2.15;g.add(head);const pack=new THREE.Mesh(new THREE.BoxGeometry(.7,.7,.3),mat(0x263237));pack.position.set(0,1.3,.45);g.add(pack);const blaster=new THREE.Mesh(new THREE.BoxGeometry(.16,.18,1.05),mat(0x151c20,.3));blaster.position.set(.5,1.45,-.35);g.add(blaster);g.position.set(p.x,0,p.z);scene.add(g);return g;};
    const makeDrone=(d:Drone)=>{const g=new THREE.Group();const size=d.kind==="COMMANDER"?.9:.62;const core=new THREE.Mesh(new THREE.IcosahedronGeometry(size,2),new THREE.MeshStandardMaterial({color:d.kind==="TANK"?0xff744d:0x5cf2e2,emissive:d.kind==="TANK"?0x7a1605:0x0c615e,emissiveIntensity:1.8,metalness:.75,roughness:.15}));core.userData.targetId=d.id;core.castShadow=true;g.add(core);for(let i=0;i<2;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry((d.kind==="COMMANDER"?1.3:.92)+i*.16,.055,8,32),new THREE.MeshBasicMaterial({color:i?0x5cf2e2:0xffb000}));ring.rotation.set(Math.PI/2,i*.7,0);ring.userData.targetId=d.id;g.add(ring)}for(let i=0;i<4;i++){const fin=new THREE.Mesh(new THREE.BoxGeometry(.12,.12,.65),mat(0x27383c,.25));fin.position.set(Math.sin(i*Math.PI/2)*.85,0,Math.cos(i*Math.PI/2)*.85);fin.rotation.y=i*Math.PI/2;fin.userData.targetId=d.id;g.add(fin)}g.position.set(d.x,2.4,d.z);scene.add(g);return g;};
    let orbit=0,drag=false,moved=false,px=0;const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();const down=(e:PointerEvent)=>{drag=true;moved=false;px=e.clientX;renderer.domElement.setPointerCapture(e.pointerId);};const move=(e:PointerEvent)=>{if(!drag)return;const dx=e.clientX-px;if(Math.abs(dx)>2)moved=true;orbit-=dx*.005;px=e.clientX;};const up=(e:PointerEvent)=>{drag=false;if(moved)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height*2-1));ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(clickables,true)[0];if(hit)latest.current.onTarget?.(String(hit.object.userData.targetId));};renderer.domElement.addEventListener("pointerdown",down);renderer.domElement.addEventListener("pointermove",move);renderer.domElement.addEventListener("pointerup",up);renderer.domElement.style.touchAction="none";
    const desired=new THREE.Vector3(),look=new THREE.Vector3(),clock=new THREE.Clock();let raf=0;const tick=()=>{raf=requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.05),smooth=1-Math.exp(-9*dt);const state=latest.current,ids=new Set(state.players.map(p=>p.id));for(const [id,m]of pilotMeshes)if(!ids.has(id)){scene.remove(m);pilotMeshes.delete(id);}for(const p of state.players){let m=pilotMeshes.get(p.id);if(!m){m=makePilot(p);pilotMeshes.set(p.id,m);}m.position.x=THREE.MathUtils.lerp(m.position.x,p.x,smooth);m.position.z=THREE.MathUtils.lerp(m.position.z,p.z,smooth);m.rotation.y=THREE.MathUtils.lerp(m.rotation.y,p.heading,smooth);}
      const live=state.targets.filter(t=>t.hp>0),tids=new Set(live.map(t=>t.id));for(const[id,m]of droneMeshes)if(!tids.has(id)){scene.remove(m);droneMeshes.delete(id);}for(const d of live){let m=droneMeshes.get(d.id);if(!m){m=makeDrone(d);droneMeshes.set(d.id,m);}m.position.y=2.5+Math.sin(performance.now()*.002+ d.x)*.28;m.rotation.y+=.018;const scale=state.tracker?1.22:1;m.scale.lerp(new THREE.Vector3(scale,scale,scale),.12);}clickables=[...droneMeshes.values()].flatMap(g=>g.children);
      const me=state.players.find(p=>p.id===state.meId)??state.players[0];if(me){const bob=reduceMotion?0:Math.sin(performance.now()*.0014)*.12;desired.set(me.x+Math.sin(orbit)*15,14+bob,me.z+Math.cos(orbit)*15);camera.position.lerp(desired,1-Math.exp(-4.5*dt));look.set(me.x,1.2,me.z);camera.lookAt(look);}renderer.render(scene,camera);};tick();
    const resize=()=>{camera.aspect=mount.clientWidth/Math.max(1,mount.clientHeight);camera.updateProjectionMatrix();renderer.setSize(mount.clientWidth,mount.clientHeight);};const observer=new ResizeObserver(resize);observer.observe(mount);
    return()=>{cancelAnimationFrame(raf);observer.disconnect();renderer.domElement.removeEventListener("pointerdown",down);renderer.domElement.removeEventListener("pointermove",move);renderer.domElement.removeEventListener("pointerup",up);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>m.dispose());}});renderer.dispose();mount.replaceChildren();};
  },[level,quality,reduceMotion]);
  return <div ref={host} className="arena-scene" aria-label="Interactive 3D arena. Use WASD or the direction controls to move, and tap glowing drones to fire."/>;
}
