"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, ClipboardCheck, Copy, Eye, LogOut, Play, Radio, RotateCcw, Shield, Users, Vote, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";

type Session={roomCode:string;playerId:string;token:string;profileKey:string};
type Player={id:string;name:string;slot:number;x:number;z:number;heading:number;score:number;hits:number;perk:string;role?:string};
type Task={id:string;room:string;name:string;x:number;z:number;done:boolean};
type Game={room:{code:string;status:"waiting"|"playing"|"meeting"|"victory";hostPlayerId:string;winner:string|null};myRole:string|null;players:Player[];tasks:Task[];leaderboard:{name:string;totalScore:number;matches:number}[]};
const SESSION_KEY="signal-saboteurs-session",PROFILE_KEY="signal-saboteurs-profile";
const COLORS=["#67e8f9","#fbbf24","#fb7185","#a78bfa","#4ade80","#f97316","#38bdf8","#f472b6"];
const safe=<T,>(raw:string|null)=>{try{return raw?JSON.parse(raw) as T:null}catch{return null}};
const makeKey=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;

export default function Home(){
  const [session,setSession]=useState<Session|null>(null),[game,setGame]=useState<Game|null>(null),[name,setName]=useState(""),[code,setCode]=useState(""),[profileKey,setProfileKey]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[roleOpen,setRoleOpen]=useState(false);const lastMove=useRef(0);
  useEffect(()=>{let key=localStorage.getItem(PROFILE_KEY);if(!key){key=makeKey();localStorage.setItem(PROFILE_KEY,key)}setProfileKey(key);const query=new URLSearchParams(location.search).get("room")?.toUpperCase()??"";if(query)setCode(query.slice(0,6));const stored=safe<Session>(localStorage.getItem(SESSION_KEY));if(stored&&(!query||query===stored.roomCode))setSession(stored)},[]);
  const enter=useCallback(async(action:"create"|"join")=>{if(name.trim().length<2||!profileKey)return;setBusy(true);setError("");try{const r=await fetch("/api/arena",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,name,roomCode:code,profileKey})});const data=await r.json() as Game&{playerId?:string;token?:string;error?:string};if(!r.ok)throw new Error(data.error||"Could not connect.");const next={roomCode:data.room.code,playerId:data.playerId!,token:data.token!,profileKey};localStorage.setItem(SESSION_KEY,JSON.stringify(next));setSession(next);setGame(data);history.replaceState({},"",`?room=${data.room.code}`)}catch(e){setError(e instanceof Error?e.message:"Could not connect.")}finally{setBusy(false)}},[name,code,profileKey]);
  useEffect(()=>{if(!session)return;let live=true;const poll=async()=>{try{const r=await fetch(`/api/arena?room=${session.roomCode}&player=${session.playerId}&token=${session.token}`,{cache:"no-store"});const data=await r.json() as Game&{error?:string};if(!r.ok)throw new Error(data.error||"Signal lost.");if(live){setGame(previous=>{if(previous?.room.status==="waiting"&&data.room.status==="playing")setRoleOpen(true);return data});setError("")}}catch(e){if(live)setError(e instanceof Error?e.message:"Signal lost.")}};void poll();const id=setInterval(poll,700);return()=>{live=false;clearInterval(id)}},[session]);
  const act=useCallback(async(action:string,extra:Record<string,unknown>={})=>{if(!session)return null;setBusy(true);setError("");try{const r=await fetch("/api/arena",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,roomCode:session.roomCode,playerId:session.playerId,token:session.token,...extra})});const data=await r.json() as Game&{error?:string};if(!r.ok)throw new Error(data.error||"Action failed.");setGame(data);return data}catch(e){setError(e instanceof Error?e.message:"Action failed.");return null}finally{setBusy(false)}},[session]);
  const me=game?.players.find(p=>p.id===session?.playerId),active=me?.perk!=="QUARANTINED",isHost=me?.id===game?.room.hostPlayerId;
  const move=useCallback((dx:number,dz:number)=>{if(!game||!me||!active||game.room.status!=="playing"||Date.now()-lastMove.current<90)return;lastMove.current=Date.now();const x=Math.max(-16,Math.min(16,me.x+dx*1.5)),z=Math.max(-12,Math.min(12,me.z+dz*1.5));setGame({...game,players:game.players.map(p=>p.id===me.id?{...p,x,z}:p)});void act("move",{x,z,heading:Math.atan2(dx,dz)})},[game,me,active,act]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches("input,button"))return;const moves:Record<string,[number,number]>={w:[0,-1],ArrowUp:[0,-1],s:[0,1],ArrowDown:[0,1],a:[-1,0],ArrowLeft:[-1,0],d:[1,0],ArrowRight:[1,0]};if(moves[e.key]){e.preventDefault();move(...moves[e.key])}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[move]);
  const nearestTask=useMemo(()=>game?.tasks.filter(t=>!t.done).sort((a,b)=>Math.hypot(a.x-(me?.x??0),a.z-(me?.z??0))-Math.hypot(b.x-(me?.x??0),b.z-(me?.z??0)))[0],[game?.tasks,me?.x,me?.z]);
  const nearestPlayer=useMemo(()=>game?.players.filter(p=>p.id!==me?.id&&p.perk==="ACTIVE").sort((a,b)=>Math.hypot(a.x-(me?.x??0),a.z-(me?.z??0))-Math.hypot(b.x-(me?.x??0),b.z-(me?.z??0)))[0],[game?.players,me?.id,me?.x,me?.z]);
  const leave=()=>{localStorage.removeItem(SESSION_KEY);setSession(null);setGame(null);history.replaceState({},"","/")};

  if(!session)return <main className="start-screen"><div className="stars"/><section className="start-copy"><p className="kicker"><Radio/> TRANSMISSION 09</p><h1>SIGNAL<br/><span>SABOTEURS</span></h1><p>A hidden Glitch is inside the station. Repair the signal, watch the crew, and trust nobody too quickly.</p><ol><li><b>1</b> Complete terminals to restore the station.</li><li><b>2</b> Call a meeting when someone acts suspicious.</li><li><b>3</b> Vote out every Glitch before they take control.</li></ol></section><section className="join-card"><header><Eye/><div><small>JOIN INVESTIGATION</small><strong>No login needed</strong></div></header><label>CODENAME<Input value={name} onChange={e=>setName(e.target.value.slice(0,18))} placeholder="Enter your name"/></label><Button disabled={busy||name.trim().length<2} onClick={()=>void enter("create")}><Play/>Create private room</Button><div className="or"><span/>OR JOIN WITH CODE<span/></div><div className="join-fields"><Input aria-label="Room code" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6))} placeholder="ROOM CODE"/><Button variant="outline" disabled={busy||code.length!==6||name.trim().length<2} onClick={()=>void enter("join")}>Join</Button></div>{error&&<p className="error">{error}</p>}<small>4–8 players · Works across phones and laptops</small></section></main>;
  if(!game)return <main className="loading"><Radio/><p>Tuning station frequency…</p></main>;
  if(game.room.status==="waiting")return <main className="lobby-screen"><div className="stars"/><header className="topbar"><b>SIGNAL <span>SABOTEURS</span></b><button onClick={leave}><LogOut/> Leave</button></header><section className="lobby-shell"><div className="lobby-main"><p className="kicker">PRIVATE FREQUENCY</p><h2>Assemble the crew</h2><p>Share the code. The host can begin when at least four investigators are connected.</p><div className="code-box"><span>{game.room.code}</span><button onClick={()=>void navigator.clipboard.writeText(`${location.origin}/?room=${game.room.code}`)}><Copy/> Copy invite</button></div><div className="crew-grid">{game.players.map(p=><article key={p.id}><div className="avatar" style={{"--crew":COLORS[p.slot]} as React.CSSProperties}><i/></div><strong>{p.name}</strong><small>{p.id===game.room.hostPlayerId?"HOST":"READY"}</small></article>)}{Array.from({length:8-game.players.length},(_,i)=><article className="empty" key={i}><div className="avatar"><Users/></div><strong>OPEN SLOT</strong><small>WAITING</small></article>)}</div>{isHost?<Button className="launch" disabled={busy||game.players.length<4} onClick={()=>void act("start")}><Play/>Begin investigation ({game.players.length}/4 minimum)</Button>:<p className="waiting"><Radio/> Waiting for the host…</p>}{error&&<p className="error">{error}</p>}</div><aside><h3>HOW TO WIN</h3><div><Shield/><p><b>OPERATORS</b><span>Finish all eight tasks or vote out every Glitch.</span></p></div><div><Zap/><p><b>GLITCHES</b><span>Disrupt tasks and reduce the active crew to equal numbers.</span></p></div><small>Roles are assigned secretly when the match begins.</small></aside></section></main>;

  const done=game.tasks.filter(t=>t.done).length,nearTask=nearestTask&&Math.hypot(nearestTask.x-(me?.x??0),nearestTask.z-(me?.z??0))<=5,nearPlayer=nearestPlayer&&Math.hypot(nearestPlayer.x-(me?.x??0),nearestPlayer.z-(me?.z??0))<=4;
  return <main className={`game-screen ${game.myRole==="GLITCH"?"is-glitch":""}`}><header className="gamebar"><div className="game-logo"><Radio/><b>SIGNAL <span>SABOTEURS</span></b></div><div className="task-progress"><span>STATION SIGNAL</span><i><b style={{width:`${done/Math.max(1,game.tasks.length)*100}%`}}/></i><strong>{done}/{game.tasks.length}</strong></div><div className="room-tag">ROOM {game.room.code}</div></header><section className="station"><div className="grid-lines"/>{game.tasks.map(t=><button key={t.id} className={`terminal ${t.done?"done":""}`} style={{left:`${(t.x+18)/36*100}%`,top:`${(t.z+14)/28*100}%`}} onClick={()=>!t.done&&void act("task",{targetId:t.id})}><ClipboardCheck/><span>{t.room}</span><small>{t.done?"RESTORED":t.name}</small></button>)}{game.players.map(p=><div key={p.id} className={`player ${p.id===me?.id?"me":""} ${p.perk==="QUARANTINED"?"ghost":""}`} style={{left:`${(p.x+18)/36*100}%`,top:`${(p.z+14)/28*100}%`,"--crew":COLORS[p.slot]} as React.CSSProperties}><div className="avatar"><i/></div><span>{p.name}</span>{p.id===me?.id&&<small>YOU</small>}</div>)}<div className="station-name">ORPHEUS RESEARCH STATION · DECK 4</div></section><aside className="objective-card"><p>YOUR ROLE</p><h2>{game.myRole==="GLITCH"?<><Zap/>GLITCH</>:<><Shield/>OPERATOR</>}</h2><span>{game.myRole==="GLITCH"?"Blend in. Fake tasks. Control the station.":"Restore every terminal. Find the hidden Glitch."}</span><div className="task-list">{game.tasks.map(t=><div key={t.id} className={t.done?"complete":""}>{t.done?<Check/>:<i/>}<span>{t.name}<small>{t.room}</small></span></div>)}</div></aside><aside className="crew-panel"><p><Users/> CREW STATUS</p>{game.players.map(p=><div key={p.id} className={p.perk==="QUARANTINED"?"offline":""}><i style={{background:COLORS[p.slot]}}/><span>{p.name}</span><b>{p.perk==="QUARANTINED"?"QUARANTINED":p.hits>0&&game.room.status==="meeting"?"VOTED":"ACTIVE"}</b></div>)}</aside><div className="move-pad"><button onClick={()=>move(0,-1)}><ArrowUp/></button><button onClick={()=>move(-1,0)}><ArrowLeft/></button><button onClick={()=>move(0,1)}><ArrowDown/></button><button onClick={()=>move(1,0)}><ArrowRight/></button></div><div className="actions"><button className="meeting" disabled={!active||game.room.status!=="playing"} onClick={()=>void act("meeting")}><AlertTriangle/><span>MEETING</span></button>{game.myRole==="GLITCH"?<><button disabled={!active||!nearPlayer} onClick={()=>nearestPlayer&&void act("erase",{targetPlayerId:nearestPlayer.id})}><Zap/><span>DESYNC</span></button><button disabled={!active} onClick={()=>void act("disrupt")}><Radio/><span>DISRUPT</span></button></>:<button disabled={!active||!nearTask} onClick={()=>nearestTask&&void act("task",{targetId:nearestTask.id})}><ClipboardCheck/><span>USE</span></button>}</div>{!active&&<div className="spectator"><Eye/> You are quarantined. Watch the investigation.</div>}{error&&<div className="toast">{error}<button onClick={()=>setError("")}>×</button></div>}

  <Dialog open={roleOpen} onOpenChange={setRoleOpen}><DialogContent className={`role-dialog ${game.myRole==="GLITCH"?"red":""}`}><div className="role-icon">{game.myRole==="GLITCH"?<Zap/>:<Shield/>}</div><p className="kicker">CLASSIFIED ASSIGNMENT</p><DialogTitle>You are {game.myRole==="GLITCH"?"the Glitch":"an Operator"}</DialogTitle><DialogDescription>{game.myRole==="GLITCH"?"Stay unnoticed. Fake repairs, disrupt restored terminals, and quietly desync nearby players.":"Complete nearby terminals. Watch how the crew moves, call meetings, and vote carefully."}</DialogDescription><Button onClick={()=>setRoleOpen(false)}>Enter station</Button></DialogContent></Dialog>
  <Dialog open={game.room.status==="meeting"}><DialogContent className="meeting-dialog" showCloseButton={false}><div className="meeting-alert"><Vote/></div><p className="kicker">EMERGENCY MEETING</p><DialogTitle>Who is the Glitch?</DialogTitle><DialogDescription>Discuss outside the game, then choose one active player. Voting ends automatically when everyone has voted.</DialogDescription><div className="vote-grid">{game.players.filter(p=>p.perk==="ACTIVE").map(p=><button key={p.id} disabled={!active||Boolean(me?.hits)} onClick={()=>void act("vote",{targetPlayerId:p.id})}><div className="avatar" style={{"--crew":COLORS[p.slot]} as React.CSSProperties}><i/></div><span>{p.name}<small>{p.id===me?.id?"YOU":p.hits>0?"VOTE LOCKED":"AWAITING VOTE"}</small></span><Vote/></button>)}</div>{me?.hits?<p className="waiting"><Radio/> Vote submitted. Waiting for the crew…</p>:<p className="meeting-tip">Pick carefully. A tie means nobody is quarantined.</p>}</DialogContent></Dialog>
  <Dialog open={game.room.status==="victory"}><DialogContent className="victory-dialog" showCloseButton={false}><div className="role-icon">{game.room.winner==="GLITCHES"?<Zap/>:<Shield/>}</div><p className="kicker">INVESTIGATION COMPLETE</p><DialogTitle>{game.room.winner} WIN</DialogTitle><DialogDescription>{game.room.winner==="GLITCHES"?"The anomaly gained control of the station.":"The signal is stable and every hidden Glitch has been contained."}</DialogDescription><div className="reveal-list">{game.players.map(p=><div key={p.id}><i style={{background:COLORS[p.slot]}}/><span>{p.name}</span><b>{p.role}</b></div>)}</div>{isHost?<Button onClick={()=>void act("reset")}><RotateCcw/>Play again</Button>:<p className="waiting">Waiting for the host to restart…</p>}</DialogContent></Dialog></main>;
}
