"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Crosshair, Users, Copy, Play, Radio, Trophy, Zap, Gauge, ScanLine, RotateCcw, LogOut, ChevronUp, ChevronDown, ChevronLeft, ChevronRight, Settings2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { ArenaScene } from "./ArenaScene";

type Session={roomCode:string;playerId:string;token:string;profileKey:string};
type Pilot={id:string;name:string;slot:number;x:number;z:number;heading:number;score:number;hits:number;shots:number;weapon:string;perk:string;joinedAt:number;lastSeenAt:number};
type Drone={id:string;x:number;z:number;hp:number;maxHp:number;kind:string;targetIndex:number;level:number;updatedAt:number;roomId:string};
type Game={room:{code:string;status:"waiting"|"playing"|"upgrade"|"victory";hostPlayerId:string;level:number;startedAt:number|null};players:Pilot[];targets:Drone[];leaderboard:{name:string;totalScore:number;bestLevel:number;matches:number}[]};
type ErrorData={error?:string};
const SESSION_KEY="echo-dropzone-session",PROFILE_KEY="echo-dropzone-profile";
const SETTINGS_KEY="echo-dropzone-settings";
type Settings={quality:"performance"|"balanced"|"cinematic";controlScale:number;leftHanded:boolean;compactHud:boolean;reduceMotion:boolean};
const DEFAULT_SETTINGS:Settings={quality:"balanced",controlScale:100,leftHanded:false,compactHud:false,reduceMotion:false};
const LEVELS=[{name:"Container Circuit",place:"STACKYARD 07",brief:"Thread the cargo lanes and clear 8 scout drones."},{name:"Coastal Airstrip",place:"TIDEBASE RUNWAY",brief:"Long sightlines, armored drones and faster flanks."},{name:"Wildland Relay",place:"VERDANT OUTPOST",brief:"Open terrain. Disable the commander to finish the operation."}];
const WEAPONS=[{id:"PULSE_SIDEARM",name:"Pulse Sidearm",level:1,stat:"28 power · balanced",desc:"Reliable starter blaster."},{id:"VECTOR_CARBINE",name:"Vector Carbine",level:2,stat:"22 power · rapid",desc:"Fast follow-up shots."},{id:"SCATTER_CANNON",name:"Scatter Cannon",level:2,stat:"48 power · heavy",desc:"Slow, high-impact bursts."},{id:"ARC_MARKSMAN",name:"Arc Marksman",level:3,stat:"72 power · precision",desc:"Maximum single-shot power."}];
const PERKS=[{id:"BOOST_THRUST",name:"Boost Thrusters",icon:Gauge,desc:"Move 40% faster."},{id:"POWER_CORE",name:"Power Core",icon:Zap,desc:"Deal 25% more damage."},{id:"TRACKER_ARRAY",name:"Tracker Array",icon:ScanLine,desc:"Larger highlighted targets."}];
const DEMO_PLAYERS=[{id:"demo",name:"Pilot",slot:0,x:0,z:9,heading:0,score:0,hits:0,shots:0,weapon:"PULSE_SIDEARM",perk:"NONE",joinedAt:0,lastSeenAt:0}];
const DEMO_TARGETS=[{id:"d1",x:-9,z:-5,hp:56,maxHp:56,kind:"SCOUT",targetIndex:0,level:1,updatedAt:0,roomId:"demo"},{id:"d2",x:4,z:-8,hp:70,maxHp:70,kind:"GUARD",targetIndex:1,level:1,updatedAt:0,roomId:"demo"},{id:"d3",x:10,z:2,hp:56,maxHp:56,kind:"SCOUT",targetIndex:2,level:1,updatedAt:0,roomId:"demo"}];
const safe=<T,>(raw:string|null)=>{try{return raw?JSON.parse(raw) as T:null}catch{return null}};
const makeProfileKey=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;

export default function Home(){
  const [session,setSession]=useState<Session|null>(null),[game,setGame]=useState<Game|null>(null),[name,setName]=useState(""),[code,setCode]=useState(""),[profileKey,setProfileKey]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[weapon,setWeapon]=useState("PULSE_SIDEARM"),[perk,setPerk]=useState("BOOST_THRUST"),[settings,setSettings]=useState<Settings>(DEFAULT_SETTINGS),[settingsOpen,setSettingsOpen]=useState(false); const lastFire=useRef(0),holdRef=useRef<ReturnType<typeof setInterval>|null>(null);
  useEffect(()=>{let key=localStorage.getItem(PROFILE_KEY);if(!key){key=makeProfileKey();localStorage.setItem(PROFILE_KEY,key)}setProfileKey(key);setSettings({...DEFAULT_SETTINGS,...safe<Settings>(localStorage.getItem(SETTINGS_KEY))});const query=new URLSearchParams(location.search).get("room")?.toUpperCase()??"";if(query)setCode(query.slice(0,6));const stored=safe<Session>(localStorage.getItem(SESSION_KEY));if(stored&&(!query||query===stored.roomCode))setSession(stored);},[]);
  useEffect(()=>{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))},[settings]);
  const enter=useCallback(async(action:"create"|"join",toolName?:string,toolCode?:string)=>{const callsign=(toolName??name).trim(),room=(toolCode??code).trim().toUpperCase();if(!callsign||!profileKey)return {ok:false,error:"Enter your callsign."};setBusy(true);setError("");try{const r=await fetch("/api/arena",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,name:callsign,roomCode:room,profileKey})});const data=await r.json() as Game&ErrorData&{playerId?:string;token?:string};if(!r.ok)throw new Error(data.error||"Could not connect.");const next={roomCode:data.room.code,playerId:data.playerId!,token:data.token!,profileKey};localStorage.setItem(SESSION_KEY,JSON.stringify(next));setSession(next);setGame(data);history.replaceState({},"",`?room=${data.room.code}`);return {ok:true,roomCode:data.room.code};}catch(e){const message=e instanceof Error?e.message:"Could not connect.";setError(message);return {ok:false,error:message};}finally{setBusy(false)}},[name,code,profileKey]);
  useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool?:(tool:unknown,options?:unknown)=>unknown}}).modelContext;if(!mc?.registerTool)return;const life=new AbortController();try{void Promise.resolve(mc.registerTool({name:"create_echo_squad",title:"Create Echo Dropzone squad",description:"Create a new Echo Dropzone co-op room.",inputSchema:{type:"object",properties:{callsign:{type:"string",minLength:2,maxLength:18}},required:["callsign"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>enter("create",String((input as{callsign?:unknown}).callsign??""))},{signal:life.signal}));void Promise.resolve(mc.registerTool({name:"join_echo_squad",title:"Join Echo Dropzone squad",description:"Join an existing room with a six-character squad code.",inputSchema:{type:"object",properties:{callsign:{type:"string",minLength:2,maxLength:18},roomCode:{type:"string",minLength:6,maxLength:6}},required:["callsign","roomCode"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const v=input as{callsign?:unknown;roomCode?:unknown};return enter("join",String(v.callsign??""),String(v.roomCode??""));}},{signal:life.signal}));}catch{}return()=>life.abort();},[enter]);
  useEffect(()=>{if(!session)return;let live=true;const poll=async()=>{try{const r=await fetch(`/api/arena?room=${session.roomCode}&player=${session.playerId}&token=${session.token}`,{cache:"no-store"});const data=await r.json() as Game&ErrorData;if(!r.ok)throw new Error(data.error||"Connection lost.");if(live){setGame(data);setError("");}}catch(e){if(live)setError(e instanceof Error?e.message:"Connection lost.")}};void poll();const id=setInterval(poll,650);return()=>{live=false;clearInterval(id)}},[session]);
  const act=useCallback(async(action:string,extra:Record<string,unknown>={})=>{if(!session)return null;setBusy(true);setError("");try{const r=await fetch("/api/arena",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,roomCode:session.roomCode,playerId:session.playerId,token:session.token,...extra})});const data=await r.json() as Game&ErrorData;if(!r.ok)throw new Error(data.error||"Action failed.");setGame(data);return data;}catch(e){setError(e instanceof Error?e.message:"Action failed.");return null}finally{setBusy(false)}},[session]);
  const me=game?.players.find(p=>p.id===session?.playerId),isHost=game?.room.hostPlayerId===me?.id,alive=game?.targets.filter(t=>t.hp>0)??[];
  const fire=useCallback(async(targetId:string)=>{if(!session||!game||game.room.status!=="playing"||Date.now()-lastFire.current<170)return;lastFire.current=Date.now();try{const r=await fetch("/api/arena",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"shoot",roomCode:session.roomCode,playerId:session.playerId,token:session.token,targetId})});const data=await r.json() as Game&ErrorData;if(r.ok)setGame(data);else if(r.status!==429)setError(data.error||"Shot missed.");}catch{setError("Connection interrupted.")}},[session,game]);
  const nudge=useCallback(async(dx:number,dz:number)=>{if(!session||!game||!me||game.room.status!=="playing")return;const speed=me.perk==="BOOST_THRUST"?1.4:1;const x=Math.max(-18,Math.min(18,me.x+dx*speed)),z=Math.max(-16,Math.min(16,me.z+dz*speed)),heading=Math.atan2(dx,dz);setGame({...game,players:game.players.map(p=>p.id===me.id?{...p,x,z,heading}:p)});try{await fetch("/api/arena",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"move",roomCode:session.roomCode,playerId:session.playerId,token:session.token,x,z,heading})});}catch{}},[session,game,me]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches("input,textarea,button"))return;const moves:Record<string,[number,number]>={w:[0,-1],ArrowUp:[0,-1],s:[0,1],ArrowDown:[0,1],a:[-1,0],ArrowLeft:[-1,0],d:[1,0],ArrowRight:[1,0]};if(moves[e.key]){e.preventDefault();void nudge(...moves[e.key]);}if(e.code==="Space"&&alive[0]){e.preventDefault();void fire(alive[0].id);}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[nudge,fire,alive]);
  useEffect(()=>{if(game?.room.status==="upgrade"){const unlocked=WEAPONS.filter(w=>w.level<=game.room.level);setWeapon(unlocked[unlocked.length-1].id);setPerk(me?.perk&&me.perk!=="NONE"?me.perk:"BOOST_THRUST")}},[game?.room.status,game?.room.level,me?.perk]);
  const closest=useMemo(()=>alive.slice().sort((a,b)=>Math.hypot(a.x-(me?.x??0),a.z-(me?.z??0))-Math.hypot(b.x-(me?.x??0),b.z-(me?.z??0)))[0],[alive,me?.x,me?.z]);
  const leave=()=>{localStorage.removeItem(SESSION_KEY);setSession(null);setGame(null);history.replaceState({},"","/")};
  const deploy=async()=>{const chosen=await act("choose",{weapon,perk});if(chosen&&isHost)await act("next")};
  const updateSetting=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(current=>({...current,[key]:value}));
  const startMove=(dx:number,dz:number)=>{void nudge(dx,dz);if(holdRef.current)clearInterval(holdRef.current);holdRef.current=setInterval(()=>void nudge(dx,dz),125)};
  const stopMove=()=>{if(holdRef.current)clearInterval(holdRef.current);holdRef.current=null};
  const settingsPanel=<>{settingsOpen&&<div className="settings-backdrop" onClick={()=>setSettingsOpen(false)}/>}<aside className={`settings-panel ${settingsOpen?"open":""}`} aria-hidden={!settingsOpen}><header><div><small>DISPLAY & CONTROLS</small><strong>Game settings</strong></div><button onClick={()=>setSettingsOpen(false)} aria-label="Close settings"><X/></button></header><label>GRAPHICS QUALITY<select value={settings.quality} onChange={e=>updateSetting("quality",e.target.value as Settings["quality"])}><option value="performance">Performance</option><option value="balanced">Balanced</option><option value="cinematic">Cinematic</option></select></label><label>BUTTON SIZE <b>{settings.controlScale}%</b><input type="range" min="85" max="125" step="5" value={settings.controlScale} onChange={e=>updateSetting("controlScale",Number(e.target.value))}/></label><label className="toggle"><span>LEFT-HANDED CONTROLS<small>Moves action controls to the left.</small></span><input type="checkbox" checked={settings.leftHanded} onChange={e=>updateSetting("leftHanded",e.target.checked)}/></label><label className="toggle"><span>COMPACT HUD<small>Shows more of the arena.</small></span><input type="checkbox" checked={settings.compactHud} onChange={e=>updateSetting("compactHud",e.target.checked)}/></label><label className="toggle"><span>REDUCE CAMERA MOTION<small>Disables the subtle camera drift.</small></span><input type="checkbox" checked={settings.reduceMotion} onChange={e=>updateSetting("reduceMotion",e.target.checked)}/></label><button className="reset-settings" onClick={()=>setSettings(DEFAULT_SETTINGS)}>RESET DEFAULTS</button></aside></>;

  if(!session)return <main className="entry"><ArenaScene level={1} players={DEMO_PLAYERS} targets={DEMO_TARGETS} meId="demo"/><div className="shade"/><header className="brand"><span><Crosshair/>ECHO</span><b>DROPZONE</b><small>CO-OP ARENA / 2–4 PILOTS</small></header><section className="entry-card"><p className="eyebrow">OPERATION READY</p><h1>Build a squad.<br/><i>Clear the zone.</i></h1><p className="intro">Three evolving 3D arenas. Every clear unlocks stronger blasters and a new tactical advantage.</p><label>CALLSIGN<Input placeholder="Enter pilot name" value={name} onChange={e=>setName(e.target.value.slice(0,18))}/></label><Button disabled={busy||name.trim().length<2||!profileKey} onClick={()=>void enter("create")}><Play/>Create squad</Button><div className="join-row"><Input aria-label="Room code" placeholder="ROOM CODE" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6))}/><Button variant="outline" disabled={busy||code.length!==6||name.trim().length<2} onClick={()=>void enter("join")}>Join</Button></div>{error&&<p className="error">{error}</p>}</section><aside className="roadmap"><p>3-LEVEL OPERATION</p>{LEVELS.map((l,i)=><article key={l.name}><b>0{i+1}</b><div><strong>{l.name}</strong><span>{i===0?"Sidearm":i===1?"Carbine + Cannon":"Arc Marksman"}</span></div></article>)}</aside></main>;
  if(!game)return <main className="loading"><Crosshair/><p>Linking to squad…</p></main>;
  if(game.room.status==="waiting")return <main className="lobby"><ArenaScene level={1} players={game.players} targets={DEMO_TARGETS} meId={session.playerId}/><div className="shade"/><header className="brand compact"><span><Crosshair/>ECHO</span><b>DROPZONE</b></header><section className="lobby-card"><p className="eyebrow">SQUAD FREQUENCY</p><div className="room-code"><span>{game.room.code}</span><button onClick={()=>void navigator.clipboard.writeText(`${location.origin}/?room=${game.room.code}`)} aria-label="Copy room invitation"><Copy/></button></div><p>Send this code to 1–3 teammates. Progress and scores sync across every screen.</p><div className="squad-list">{game.players.map(p=><article key={p.id}><b>0{p.slot+1}</b><span>{p.name}<small>{p.id===game.room.hostPlayerId?"SQUAD LEADER":"PILOT"}</small></span><i/></article>)}{Array.from({length:4-game.players.length},(_,i)=><article className="empty" key={i}><b>--</b><span>OPEN SLOT<small>WAITING</small></span></article>)}</div>{isHost?<Button disabled={busy||game.players.length<2} onClick={()=>void act("start")}><Radio/>Deploy squad</Button>:<p className="waiting">Waiting for the squad leader…</p>}<button className="leave" onClick={leave}><LogOut/>Leave squad</button>{error&&<p className="error">{error}</p>}</section></main>;

  const accuracy=me?.shots?Math.round(me.hits/me.shots*100):0,level=LEVELS[game.room.level-1]??LEVELS[2];
  return <main className={`arena ${settings.compactHud?"hud-compact":""} ${settings.leftHanded?"controls-left":""}`} style={{"--control-scale":settings.controlScale/100} as React.CSSProperties}><ArenaScene level={game.room.level} players={game.players} targets={game.targets} meId={session.playerId} tracker={me?.perk==="TRACKER_ARRAY"} quality={settings.quality} reduceMotion={settings.reduceMotion} onTarget={id=>void fire(id)}/><div className="vignette"/><div className="scanlines"/><header className="hud-top"><div className="mini-brand"><Crosshair/><span>ECHO <b>DROPZONE</b></span></div><div className="compass"><small>SW</small><span>W</span><b>▾ 285</b><span>NW</span><small>N</small></div><div className="hud-actions"><div className="room-pill">ROOM {game.room.code}</div><button className="settings-trigger" onClick={()=>setSettingsOpen(true)} aria-label="Open game settings"><Settings2/></button></div></header><aside className="team-panel"><p><Users/>SQUAD {game.players.length}/4</p>{game.players.map(p=><article key={p.id} className={p.id===me?.id?"me":""}><i style={{background:["#5cf2e2","#ffb000","#ff5b57","#7899ff"][p.slot]}}/><div><strong>{p.name}</strong><small>{WEAPONS.find(w=>w.id===p.weapon)?.name}</small></div><b>{p.score}</b></article>)}</aside><aside className="mission-panel"><p>LEVEL {game.room.level}/3</p><h2>{level.name}</h2><span>{level.place}</span><div className="objective"><Crosshair/><div><small>DRONES ACTIVE</small><b>{alive.length} / {game.targets.length}</b></div></div><p className="brief">{level.brief}</p></aside><div className="crosshair" aria-hidden="true"><i/><i/></div><section className="weapon-hud"><small>ACTIVE BLASTER</small><strong>{WEAPONS.find(w=>w.id===me?.weapon)?.name}</strong><span>{me?.score??0} PTS · {accuracy}% ACC</span></section><div className="controls"><div className="dpad"><button aria-label="Move up" onPointerDown={()=>startMove(0,-1)} onPointerUp={stopMove} onPointerLeave={stopMove}><ChevronUp/></button><button aria-label="Move left" onPointerDown={()=>startMove(-1,0)} onPointerUp={stopMove} onPointerLeave={stopMove}><ChevronLeft/></button><button aria-label="Move down" onPointerDown={()=>startMove(0,1)} onPointerUp={stopMove} onPointerLeave={stopMove}><ChevronDown/></button><button aria-label="Move right" onPointerDown={()=>startMove(1,0)} onPointerUp={stopMove} onPointerLeave={stopMove}><ChevronRight/></button></div><button className="fire" disabled={!closest||game.room.status!=="playing"} onClick={()=>closest&&void fire(closest.id)}><Crosshair/><span>FIRE</span></button></div><div className="desktop-help">WASD MOVE · CLICK DRONE OR SPACE TO FIRE · DRAG TO ROTATE CAMERA</div>{settingsPanel}{error&&<div className="toast-error">{error}<button onClick={()=>setError("")}>×</button></div>}

  <Dialog open={game.room.status==="upgrade"}><DialogContent className="upgrade-dialog" showCloseButton={false}><p className="eyebrow">LEVEL {game.room.level-1} CLEAR · NEW GEAR ONLINE</p><DialogTitle>Choose your next loadout</DialogTitle><DialogDescription>Every pilot chooses one blaster and one permanent advantage for the next zone.</DialogDescription><h3>BLASTER</h3><div className="choice-grid weapons">{WEAPONS.filter(w=>w.level<=game.room.level).map(w=><button key={w.id} className={weapon===w.id?"selected":""} onClick={()=>setWeapon(w.id)}><Crosshair/><strong>{w.name}</strong><span>{w.stat}</span><small>{w.desc}</small></button>)}</div><h3>ADVANTAGE</h3><div className="choice-grid perks">{PERKS.map(p=>{const Icon=p.icon;return <button key={p.id} className={perk===p.id?"selected":""} onClick={()=>setPerk(p.id)}><Icon/><strong>{p.name}</strong><small>{p.desc}</small></button>})}</div><Button disabled={busy} onClick={()=>void deploy()}>{isHost?<><Play/>Save & launch level {game.room.level}</>:<>Save loadout</>}</Button>{!isHost&&<small className="host-note">Your squad leader controls the launch.</small>}</DialogContent></Dialog>
  <Dialog open={game.room.status==="victory"}><DialogContent className="victory-dialog" showCloseButton={false}><Trophy/><p className="eyebrow">ALL THREE ZONES SECURED</p><DialogTitle>Operation complete</DialogTitle><DialogDescription>Your squad disabled every drone. Scores are now saved to the global pilot board.</DialogDescription><div className="results">{game.players.slice().sort((a,b)=>b.score-a.score).map((p,i)=><article key={p.id}><b>#{i+1}</b><span>{p.name}<small>{p.hits} hits · {p.shots?Math.round(p.hits/p.shots*100):0}% accuracy</small></span><strong>{p.score}</strong></article>)}</div><h3>GLOBAL PILOTS</h3><ol className="leaderboard">{game.leaderboard.slice(0,5).map((p,i)=><li key={`${p.name}-${i}`}><b>{i+1}</b><span>{p.name}</span><strong>{p.totalScore}</strong></li>)}</ol>{isHost?<Button disabled={busy} onClick={()=>void act("reset")}><RotateCcw/>Run it again</Button>:<p className="host-note">Waiting for the squad leader.</p>}</DialogContent></Dialog></main>;
}
